autoweb/autoweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'pages.views.page_forbidden'
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.socialaccount.urls')),
    path(
        'accounts/', include('allauth.socialaccount.providers.google.urls')
    ),
    path(
        'accounts/', include('allauth.socialaccount.providers.yandex.urls')
    ),
    path('auth/', include('authorization.urls')),
    path('profile/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

autoweb/cart/urls.py
from django.urls import path

from .views import (add_to_cart, cart, checkout, delete_cart_item,
                    thank_you_page, update_cart_item, update_user_checkout)

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<int:pk>/', add_to_cart, name='cart_add'),
    path('update-cart-item/', update_cart_item, name='update_cart_item'),
    path('delete/<int:pk>', delete_cart_item, name='cart_delete'),
    path('checkout/', checkout, name='checkout'),
    path(
        'update-user-checkout/', update_user_checkout, name='update_checkout'
    ),
    path(
        'checkout/thank-you/<int:pk>', thank_you_page, name='thank_you'
    ),
]

autoweb/orders/urls.py
from django.urls import path

from .order2pdf import order_pdf_file
from .send_email import send_user_mail
from .views import (
    create_order_view, order_details, orders_history, cancel_order,
)

app_name = 'order'

urlpatterns = [
    path(
        'create-order/',
        create_order_view,
        name='create_order'
    ),
    path(
        'cancel-order/<int:pk>/',
        cancel_order,
        name='cancel_order'
    ),
    path(
        'order-details/<int:pk>/',
        order_details,
        name='details'
    ),
    path(
        'order-history/',
        orders_history,
        name='history'
    ),
    path(
        'order-pdf-file/<int:pk>',
        order_pdf_file,
        name='pdf_file'
    ),
    path(
        'send-email/<int:pk>',
        send_user_mail,
        name='send_email'
    ),
]

autoweb/pages/urls.py
from django.urls import path

from .views import About, Confidential, Contacts, Terms

app_name = 'pages'

urlpatterns = [
    path('about/', About.as_view(), name='about'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('confidential/', Confidential.as_view(), name='confidential'),
    path('terms-and-conditions/', Terms.as_view(), name='terms'),
]

autoweb/shop/urls.py
from django.urls import path

from .views import (HomepageView, PromotionsView, brands_detail_view,
                    brands_list_view, categories_list_view,
                    filter_products_page, product_detail_view,
                    product_list_view, promotions_detail_view, search_view,
                    subcategory_list_view)

app_name = 'shop'

urlpatterns = [
    path(
        '',
        HomepageView.as_view(),
        name='homepage'
    ),
    path(
        'categories/',
        categories_list_view,
        name='categories_list'
    ),
    path(
        '<slug:category_slug>/subcategories/',
        subcategory_list_view,
        name='subcategory_list'
    ),
    path(
        ('<slug:category_slug>/<slug:subcategory_slug>/products/'),
        product_list_view,
        name='product_list'
    ),
    path(
        '<slug:category_slug>/<slug:subcategory_slug>/<int:pk>/',
        product_detail_view,
        name='product_detail'
    ),
    path(
        'brands/',
        brands_list_view,
        name='brands_list'
    ),
    path(
        'brands/<slug:slug_brand>/',
        brands_detail_view,
        name='brand_detail'
    ),
    path(
        'search/',
        search_view,
        name='search',
    ),
    path(
        'promotions/',
        PromotionsView.as_view(),
        name='promotions',
    ),
    path(
        'promotions/<int:pk>/',
        promotions_detail_view,
        name='promotion_detail',
    ),
    path(
        'all-products/',
        filter_products_page,
        name='all_products'
    )
]

autoweb/cart/models.py
from django.contrib.auth import get_user_model
from django.db import models

from shop.models import Product

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Покупатель'
    )
    products = models.ManyToManyField(
        Product,
        through='CartItem',
        verbose_name='Товар'
    )

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def get_cart_items(self):
        cart_items = self.cartitem_set.prefetch_related('product').all()
        return cart_items

    def clear_cart(self):
        return self.get_cart_items().delete()

    @property
    def total_price(self):
        cart_items = self.get_cart_items()
        total_price = sum(
            cart_item.total_price for cart_item in cart_items
        )
        return total_price

    @property
    def count(self):
        return self.get_cart_items().count()

    def __str__(self):
        return f'Корзина {self.id} пользователя: {self.user.username}'


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        verbose_name='Корзина'
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='Товар'
    )
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество'
    )

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    @property
    def total_price(self):
        total_price = self.quantity * self.product.price
        return total_price

    def __str__(self):
        return f'Итого: {self.quantity} x {self.product.title}'

autoweb/cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from orders.services import OrderServices
from shop.models import Product
from users.forms import CustomUserEditFormCheckout
from autoweb.constants import BREADCRUMB_DATA

from .models import Cart, CartItem
from .services import CartServices
from .utils import get_pk_from_path
from .validators import check_items_in_cart, check_product_price_and_qty


@login_required
def cart(request):
    template = 'cart/cart.html'
    cart = Cart.objects.filter(user=request.user).first()

    if not cart:
        cart = Cart.objects.create(user=request.user)

    context = {
        'cart_products': CartItem.objects.filter(cart=cart),
        'cart': cart,
        'title': 'Корзина товаров',
        'description': 'Страница с корзиной товаров пользователя.',
        'breadcrumb': BREADCRUMB_DATA.get('cart')
    }

    return render(request, template, context)


@login_required
def add_to_cart(request, pk):

    if request.method == 'GET':
        path_of_next = request.build_absolute_uri()
        product_pk = get_pk_from_path(path_of_next)
        product = get_object_or_404(Product, pk=product_pk)
        return redirect(
            'shop:product_detail',
            category_slug=product.category.slug,
            subcategory_slug=product.subcategory.slug,
            pk=product_pk
        )

    if request.method == 'POST':
        product = get_object_or_404(Product, pk=pk)
        if not check_product_price_and_qty(request, product):
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        quantity = int(request.POST.get('quantity', 1))
        success_cart = CartServices.add_to_cart(
            request.user, product, quantity
        )

        if success_cart:
            messages.success(
                request, 'Товар добавлен в корзину.'
            )
        else:
            messages.warning(
                request, 'Добавлено максимально возможное количество товара.'
            )

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_cart_item(request, pk):
    CartServices.delete_cart_item(request.user, pk)

    messages.success(
        request, 'Товар успешно удалён из корзины.'
    )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def update_cart_item(request):
    if (
        request.method == 'POST'
        and request.headers.get('x-requested-with') == 'XMLHttpRequest'
    ):
        with transaction.atomic():
            cart_item_id = request.POST.get('cart_item_id')
            new_quantity = int(request.POST.get('new_quantity'))
            cart_id_value = request.POST.get('cart_id')
            if not cart_id_value:
                return JsonResponse({
                    'success': False,
                    'error': 'cart_id не обнаружен.'
                })

            cart_id = int(cart_id_value)

            cart = Cart.objects.get(pk=cart_id)
            cart_item = get_object_or_404(CartItem, id=cart_item_id)
            if new_quantity > cart_item.product.quantity:
                return JsonResponse({
                    'success': False,
                    'error': 'Нельзя добавить больше, чем есть.'
                })
            cart_item.quantity = new_quantity
            cart_item.save()
            return JsonResponse({
                'success': True,
                'cart_item_id': cart_item.id,
                'cart_item_quantity': cart_item.quantity,
                'cart_item_total_price': cart_item.total_price,
                'cart_total_price': cart.total_price
            })
    else:
        return JsonResponse({
            'success': False, 'error': 'Неверный метод запроса'
        })


@login_required
def checkout(request):
    template = 'cart/checkout.html'
    cart, cart_products = CartServices.get_cart_and_items(request.user)

    if not check_items_in_cart(request, cart_products):
        return redirect('cart:cart')

    form = CustomUserEditFormCheckout(instance=request.user)
    context = {
        'cart': cart,
        'cart_products': cart_products,
        'user': request.user,
        'form': form,
        'title': 'Оформление заказа',
        'description': 'Страница с оформлением заказа.',
        'breadcrumb': BREADCRUMB_DATA.get('checkout')
    }
    return render(request, template, context)


@login_required
def update_user_checkout(request):
    if request.method == 'POST':
        form = CustomUserEditFormCheckout(
            request.POST, instance=request.user
        )
        if form.is_valid():
            with transaction.atomic():
                form.save()
                messages.success(
                    request, 'Данные пользователя обновлены.'
                )
                return HttpResponseRedirect(reverse('cart:checkout'))
        else:
            cart, cart_products = CartServices.get_cart_and_items(request.user)
            context = {
                'cart': cart,
                'cart_products': cart_products,
                'user': request.user,
                'form': form
            }
            messages.error(
                request,
                (
                    'Пожалуйста, проверьте корректность введённых '
                    'данных пользователя.'
                )
            )
            return render(request, 'cart/checkout.html', context)
    else:
        return HttpResponseRedirect(reverse('cart:checkout'))


@login_required
def thank_you_page(request, pk):
    template = 'cart/thank_you.html'
    order, order_items = OrderServices.get_order_and_items(
        request.user, pk
    )

    if not order.is_confirmed:
        if OrderServices.confirm_order(order, order_items):
            context = {
                'order': order,
                'order_items': order_items,
                'title': 'Благодарим за заказ!',
                'description': 'Страница с оформленным заказом.'
            }
            return render(request, template, context)
        else:
            messages.error(
                request, 'Ошибка при подтверждении заказа.'
            )
            return HttpResponseRedirect(
                reverse('cart:cart')
            )
    else:
        context = {
            'order': order,
            'order_items': order_items,
            'title': 'Заказ оформлен',
            'description': 'Страница с оформленным заказом.'
        }
        return render(request, template, context)

autoweb/templates/cart/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="page-header">
  <div class="page-header__container container">
      <div class="page-header__breadcrumb">
          <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                      <a href="{% url 'shop:homepage' %}">Главная</a>
                      <svg class="breadcrumb-arrow" width="6px" height="9px">
                          <use xlink:href="/static/images/sprite.svg#arrow-rounded-right-6x9"></use>
                      </svg>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
              </ol>
          </nav>
      </div>
      <div class="page-header__title">
          <h1>{{ title }}</h1>
      </div>
  </div>
</div>

<div class="site__body">
  {% if cart_products %}
  <div class="cart block">
    <div class="container">
      <table class="cart__table cart-table">
        <thead class="cart-table__head">
          <tr class="cart-table__row">
              <th class="cart-table__column cart-table__column--image">Изображение</th>
              <th class="cart-table__column cart-table__column--product">Наименование товара</th>
              <th class="cart-table__column cart-table__column--quantity">Доступно</th>
              <th class="cart-table__column cart-table__column--price">Цена, руб.</th>
              <th class="cart-table__column cart-table__column--quantity">Количество</th>
              <th class="cart-table__column cart-table__column--total">Итого, руб.</th>
              <th class="cart-table__column cart-table__column--remove"></th>
          </tr>
        </thead>
        <tbody class="cart-table__body">
          {% for cart_item in cart_products %}
          <tr class="cart-table__row">
            <td class="cart-table__column cart-table__column--image">
              {% with cart_item.product.images.first as first_image %}
                {% if first_image %}
                <div class="product-image">
                    <a href="{{ cart_item.product.get_absolute_url }}" class="product-image__body">
                        <img class="product-image__img" src="{{ first_image.image.url }}" alt="">
                    </a>
                </div>
                {% else %}
                <div class="product-image">
                  <a href="{{ cart_item.product.get_absolute_url }}" class="product-image__body">
                      <img class="product-image__img" src="{% static 'images/image-holder.webp' %}" alt="">
                  </a>
                </div>
                {% endif %}
              {% endwith %}
            </td>
            <td class="cart-table__column cart-table__column--product">
              <a href="{{ cart_item.product.get_absolute_url }}" class="cart-table__product-name">{{ cart_item.product.title }}</a>
              <ul class="cart-table__options">
                  <li>{{ cart_item.product.subcategory }}</li>
                  <li>{{ cart_item.product.brand }}</li>
                  <li>{{ cart_item.product.article }}</li>
              </ul>
            </td>
            <td class="count cart-table__column cart-table__column--quantity" data-title="В наличии">{{ cart_item.product.quantity }}</td>
            <td class="cart-table__column cart-table__column--price" data-title="Цена">{{ cart_item.product.price }}</td>
            <td class="count cart-table__column cart-table__column--quantity" data-title="Количество">
                <div class="input-number">
                  <div class="input-number__add"></div>
                  <input type="number" min="1" value="{{ cart_item.quantity }}" class="form-control input-number__input" data-cart-item-id="{{ cart_item.id }}">
                  <div class="input-number__sub"></div>
                </div>
                <form id="update-cart-item-form" method="POST" action="{% url 'cart:update_cart_item' %}" style="display:none;">
                  {% csrf_token %}
                  <input type="hidden" id="new-quantity-input" name="new_quantity">
                  <input type="hidden" id="cart-item-id-input" name="cart_item_id">
                </form>
            </td>
            <td class="cart-table__column cart-table__column--total cart-item-total-price" data-cart-item-id="{{ cart_item.id }}" data-title="Итог">{{ cart_item.total_price }}</td>
            <td class="cart-table__column cart-table__column--remove">
              <form method="POST" action="{% url 'cart:cart_delete' cart_item.product.pk %}" style="display: inline;"
                hx-post="{% url 'cart:cart_delete' cart_item.product.pk %}"
                hx-target="body"
              >
                  {% csrf_token %}
                  <button type="submit" class="btn btn-light btn-sm btn-svg-icon">
                      <svg width="12px" height="12px">
                          <use xlink:href="/static/images/sprite.svg#cross-12"></use>
                      </svg>
                  </button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="cart__actions">
        <form class="cart__coupon-form">
        </form>
        <div class="cart__buttons">
            <a href="{% url 'shop:all_products' %}" class="btn btn-primary cart__update-button">Продолжить покупки</a>
        </div>
      </div>
    </div>
    <div class="container pt-5">
      <div class="row justify-content-end">
        <div class="col-12 col-md-7 col-lg-6 col-xl-5">
          <div class="card">
            <div class="card-body">
              <table class="cart__totals">
                <tfoot class="cart__totals-footer">
                  <tr>
                    <th>Общий итог:</th>
                    <td><b><span id="cart-total-price" data-cart-id="{{ cart.id }}">{{ cart.total_price }} руб.</span></b></td>
                  </tr>
                </tfoot>
              </table>
              <a class="btn btn-primary btn-xl btn-block cart__checkout-button" href="{% url 'cart:checkout' %}">Оформить заказ</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="block-empty__body">
    <div class="block-empty__message">В корзине пока ничего нет!</div>
    <div class="block-empty__actions">
        <a class="btn btn-primary btn-sm" href="{% url 'shop:all_products' %}">В каталог</a>
        <a class="btn btn-primary btn-sm" href="{% url 'shop:homepage' %}">На главную</a>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

autoweb/templates/cart/checkout.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block content %}

<div class="page-header">
    <div class="page-header__container container">
        <div class="page-header__breadcrumb">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'shop:homepage' %}">Главная</a>
                        <svg class="breadcrumb-arrow" width="6px" height="9px">
                            <use xlink:href="/static/images/sprite.svg#arrow-rounded-right-6x9"></use>
                        </svg>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'cart:cart' %}">Корзина товаров</a>
                        <svg class="breadcrumb-arrow" width="6px" height="9px">
                            <use xlink:href="/static/images/sprite.svg#arrow-rounded-right-6x9"></use>
                        </svg>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
                </ol>
            </nav>
        </div>
        <div class="page-header__title">
            <h1>{{ title }}</h1>
        </div>
    </div>
</div>

<div class="site__body">
    <div class="checkout block">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="card mb-lg-0">
                        <div class="card-body">
                            <h3 class="card-title">Информация о покупателе</h3>
                            <form method="post" id="customer-info-form" action="{% url 'cart:update_checkout' %}">
                                {% csrf_token %}
                                
                                {% for field in form %}
                                    <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                                        {% bootstrap_field field form_group_class='my_custom_class' %}
                                    </div>
                                {% endfor %}
                                    <div class="typography">
                                        Пожалуйста, введи корректный номер телефона, чтобы мы могли с Вами связаться при возникновении необходимости уточнения деталей заказа.
                                    </div>
                                <div class="form-group mt-5 mb-0">
                                    <button class="btn btn-primary" aria-label="Подтвердить изменения">Подтвердить изменения</button>
                                </div>
                            </form>
                        </div>
                        <div class="card-divider"></div>
                    </div>
                </div>
                <div class="col-12 col-lg-6 col-xl-5 mt-4 mt-lg-0">
                    <div class="card mb-0">
                        <div class="card-body">
                            <h3 class="card-title">Ваш заказ</h3>
                            <table class="checkout__totals">
                                <thead class="checkout__totals-header">
                                    <tr>
                                        <th>Наименование товара</th>
                                        <th>Итого, руб.</th>
                                    </tr>
                                </thead>
                                {% for cart_item in cart_products %}
                                    <tbody class="checkout__totals-products">
                                        <tr>
                                            <td>{{ cart_item.product.title }} × {{ cart_item.quantity }}</td>
                                            <td>{{ cart_item.total_price }}</td>
                                        </tr>
                                    </tbody>
                                {% endfor %}
                                <tfoot class="checkout__totals-footer">
                                    <tr>
                                        <th>Общий итог:</th>
                                        <td>{{ cart.total_price }}</td>
                                    </tr>
                                </tfoot>
                            </table>
                            <div class="payment-methods">
                                <ul class="payment-methods__list">
                                    <li class="payment-methods__item payment-methods__item--active">
                                        <label class="payment-methods__item-header">
                                            <span class="payment-methods__item-radio input-radio">
                                                <span class="input-radio__body">
                                                    <input class="input-radio__input" name="checkout_payment_method" type="radio" checked>
                                                    <span class="input-radio__circle"></span>
                                                </span>
                                            </span>
                                            <span class="payment-methods__item-title">Оплата в магазине</span>
                                        </label>
                                        <div class="payment-methods__item-container">
                                            <div class="payment-methods__item-description text-muted">
                                                На данный момент доступен только этот вариант оплаты, но мы работаем
                                                и над другими! В магазине оплата возможна как наличными, так и 
                                                банковской картой, и по QR-коду.
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="checkout__agree form-group">
                                <div class="form-check">
                                    <form method="POST" action="{% url 'order:create_order' %}">
                                        {% csrf_token %}
                                        <div class="checkout__agree form-group">
                                            <div class="form-check">
                                                <span class="form-check-input input-check">
                                                    <span class="input-check__body">
                                                        <input class="input-check__input" type="checkbox" id="checkout-terms">
                                                        <span class="input-check__box"></span>
                                                        <svg class="input-check__icon" width="9px" height="7px">
                                                            <use xlink:href="/static/images/sprite.svg#check-9x7"></use>
                                                        </svg>
                                                    </span>
                                                </span>
                                                <label class="form-check-label" for="checkout-terms">
                                                    Я прочитал и согласен <a target="_blank" href="{% url 'pages:terms' %}">с пользовательским соглашением сайта</a> 
                                                    и <a target="_blank" href="{% url 'pages:confidential' %}">политикой конфиденциальности</a>
                                                </label>
                                            </div>
                                        </div>
                                        <button type="submit" id="submit-order-button" class="btn btn-primary btn-xl btn-block" aria-label="Оформить" disabled>Оформить</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% verbatim %}
<script>
document.addEventListener('DOMContentLoaded', function () {
    // Получаем элементы формы и кнопки "Разместить заказ"
    const customerInfoForm = document.getElementById("customer-info-form");
    const orderForm = document.getElementById("order-form");
    const submitOrderBtn = document.getElementById("submit-order-button");
    const termsCheckbox = document.getElementById("checkout-terms");

    function checkFormValidity() {
        // Проверка валидности формы и состояние чекбокса "соглашения"
        if (customerInfoForm.checkValidity() && termsCheckbox.checked) {
            submitOrderBtn.removeAttribute("disabled");
        } else {
            submitOrderBtn.setAttribute("disabled", true);
        }
    }
    
    // Отслеживаем изменения формы информации о покупателе и чекбокса "соглашения"
    customerInfoForm.addEventListener("change", checkFormValidity);
    termsCheckbox.addEventListener("change", checkFormValidity);

    // Первоначальная проверка валидности формы и состояния чекбокса пользовательского соглашения
    checkFormValidity();
});
</script>
{% endverbatim %}
{% endblock %}