autoweb/authorization/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from .views import (CustomUserCreateView, CustomAuthView,
                    CustomePasswordChangeView, CustomePasswordResetView)

app_name = 'auth'

urlpatterns = [
    path(
        'registration/',
        CustomUserCreateView.as_view(),
        name='registration'
    ),
    path(
        'login/',
        CustomAuthView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'password-reset/',
        CustomePasswordResetView.as_view(
            success_url=reverse_lazy('auth:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('auth:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
    path(
        'password-change/',
        CustomePasswordChangeView.as_view(
            success_url=reverse_lazy('auth:password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password-change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
]

autoweb/autoweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'pages.views.page_forbidden'
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.socialaccount.urls')),
    path(
        'accounts/', include('allauth.socialaccount.providers.google.urls')
    ),
    path(
        'accounts/', include('allauth.socialaccount.providers.yandex.urls')
    ),
    path('auth/', include('authorization.urls')),
    path('profile/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

autoweb/cart/urls.py
from django.urls import path

from .views import (add_to_cart, cart, checkout, delete_cart_item,
                    thank_you_page, update_cart_item, update_user_checkout)

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<int:pk>/', add_to_cart, name='cart_add'),
    path('update-cart-item/', update_cart_item, name='update_cart_item'),
    path('delete/<int:pk>', delete_cart_item, name='cart_delete'),
    path('checkout/', checkout, name='checkout'),
    path(
        'update-user-checkout/', update_user_checkout, name='update_checkout'
    ),
    path(
        'checkout/thank-you/<int:pk>', thank_you_page, name='thank_you'
    ),
]

autoweb/pages/urls.py
from django.urls import path

from .views import About, Confidential, Contacts, Terms

app_name = 'pages'

urlpatterns = [
    path('about/', About.as_view(), name='about'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('confidential/', Confidential.as_view(), name='confidential'),
    path('terms-and-conditions/', Terms.as_view(), name='terms'),
]

autoweb/shop/urls.py
from django.urls import path

from .views import (HomepageView, PromotionsView, brands_detail_view,
                    brands_list_view, categories_list_view,
                    filter_products_page, product_detail_view,
                    product_list_view, promotions_detail_view, search_view,
                    subcategory_list_view)

app_name = 'shop'

urlpatterns = [
    path(
        '',
        HomepageView.as_view(),
        name='homepage'
    ),
    path(
        'categories/',
        categories_list_view,
        name='categories_list'
    ),
    path(
        '<slug:category_slug>/subcategories/',
        subcategory_list_view,
        name='subcategory_list'
    ),
    path(
        ('<slug:category_slug>/<slug:subcategory_slug>/products/'),
        product_list_view,
        name='product_list'
    ),
    path(
        '<slug:category_slug>/<slug:subcategory_slug>/<int:pk>/',
        product_detail_view,
        name='product_detail'
    ),
    path(
        'brands/',
        brands_list_view,
        name='brands_list'
    ),
    path(
        'brands/<slug:slug_brand>/',
        brands_detail_view,
        name='brand_detail'
    ),
    path(
        'search/',
        search_view,
        name='search',
    ),
    path(
        'promotions/',
        PromotionsView.as_view(),
        name='promotions',
    ),
    path(
        'promotions/<int:pk>/',
        promotions_detail_view,
        name='promotion_detail',
    ),
    path(
        'all-products/',
        filter_products_page,
        name='all_products'
    )
]

autoweb/templates/includes/account_navigation.html
{% with request.resolver_match.view_name as view_name %}
  <div class="col-12 col-lg-3 d-flex">
    <div class="account-nav flex-grow-1">
      <h4 class="account-nav__title">Навигация</h4>
      <ul>
        <li class="account-nav__item {% if view_name == 'account:profile' %}account-nav__item--active{% endif %}">
          <a href="{% url 'account:profile' %}">Профиль</a>
        </li>
        <li class="account-nav__item {% if view_name == 'account:users_auto' %}account-nav__item--active{% endif %}">
          <a href="{% url 'account:users_auto' %}">Автопарк</a>
        </li>
        <li class="account-nav__item {% if view_name == 'order:history' %}account-nav__item--active{% endif %}">
          <a href="{% url 'order:history' %}">История заказов</a>
        </li>
        <li class="account-nav__item {% if view_name == 'order:details' %}account-nav__item--active{% endif %}">
          <a href="#">Детали заказа</a>
        </li>
        <li class="account-nav__item {% if view_name == 'account:edit_profile' %}account-nav__item--active{% endif %}">
          <a href="{% url 'account:edit_profile' %}">Изменить профиль</a>
        </li>
        <li class="account-nav__item {% if view_name == 'auth:password_change' %}account-nav__item--active{% endif %}">
          <a href="{% url 'auth:password_change' %}">Изменить пароль</a>
        </li>
        &nbsp;
        <form class="account-nav__item" method="post" action="{% url 'auth:logout' %}">
          {% csrf_token %}
          <button class="btn btn-primary btn-sm mx-3" type="submit">Выйти из профиля</button>
        </form>
      </ul>
    </div>
  </div>
{% endwith %}

autoweb/templates/includes/dropcart_product.html
{% load static %}

{% for cart_item in cart_products %}
<div class="dropcart__product">
    <div class="product-image dropcart__product-image">
        {% with cart_item.product.images.first as first_image %}
            {% if first_image %}
                <div class="product-card__image product-image">
                    <a href="{{ cart_item.product.get_absolute_url }}" class="product-image__body">
                    <img class="product-image__img img-fluid" src="{{ first_image.image.url }}">
                    </a>
                </div>
            {% else %}
                <a href="{{ cart_item.product.get_absolute_url }}" class="product-image__body">
                    <img class="product-image__img" src="{% static 'images/image-holder.webp' %}">
                </a>
            {% endif %}
        {% endwith %}
    </div>
    <div class="dropcart__product-info">
        <div class="dropcart__product-name"><a href="{{ cart_item.product.get_absolute_url }}">{{ cart_item.product.title }}</a></div>
        <ul class="dropcart__product-options">
            <li>{{ cart_item.product.subcategory }}</li>
            <li>{{ cart_item.product.brand }}</li>
            <li>{{ cart_item.product.article }}</li>
        </ul>
        <div class="dropcart__product-meta">
            <span class="dropcart__product-quantity">{{ cart_item.quantity }}</span> ×
            <span class="dropcart__product-price">{{ cart_item.product.price }} руб.</span>
        </div>
    </div>
    <form method="POST" action="{% url 'cart:cart_delete' cart_item.product.pk %}" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-light btn-sm btn-svg-icon" aria-label="Удалить из корзины"
            hx-post="{% url 'cart:cart_delete' cart_item.product.pk %}"
            hx-target="body"
        >
            <svg width="12px" height="12px">
                <use xlink:href="/static/images/sprite.svg#cross-12"></use>
            </svg>
        </button>
    </form>
</div>
{% endfor %}

autoweb/templates/includes/extend_product_card.html
{% load static %}

<div class="block-products-carousel__column">
  <div class="block-products-carousel__cell">
    <div class="product-card product-card--hidden-actions ">
      <div class="product-card__info">
        {% with product.images.first as first_image %}
          {% if first_image %}
            <div class="product-card__image product-image">
              <a href="{{ product.get_absolute_url }}" class="product-image__body" aria-label="Изображение товара, перейти на страницу товара">
                <img class="product-image__img img-fluid" src="{{ first_image.image.url }}">
              </a>
            </div>
          {% else %}
            <div class="product-card__image product-image">
                <a href="{{ product.get_absolute_url }}" class="product-image__body" aria-label="Изображение отсутствует, перейти на страницу товара">
                    <img class="product-image__img" src="{% static 'images/image-holder.webp' %}" alt="">
                </a>
            </div>
          {% endif %}
        {% endwith %}
          <div class="product-card__actions">
            <div class="product-card__name">
                <a href="{{ product.get_absolute_url }}"><strong>{{ product.title }}</strong></a>
            </div>
            <div class="product-card__prices">
              Цена: {{ product.price }} руб.
            </div>
            <ul class="product__meta">
              <li>
                <a href="{{ product.category.get_absolute_url }}">{{ product.category.title }}</a>,
                <a href="{{ product.subcategory.get_absolute_url }}">{{ product.subcategory.title|lower }}</a>
              </li>
              <li>Производитель: <a href="{{ product.brand.get_absolute_url }}">{{ product.brand.title }}</a></li>
              <li>Артикул: <a href="{{ product.get_absolute_url }}">{{ product.article }}</a></li>
              <li>Доступно в наличии: {{ product.quantity }}</li>
            </ul>
        </div>
      </div>
      <div class="product-card__actions">
        <div class="product-card__buttons">
          <form class="product__options" method="POST" action="{% url 'cart:cart_add' product.pk %}">
            {% csrf_token %}
            <input class="btn btn-primary product-card__addtocart" type="submit" value="Добавить в корзину">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

autoweb/templates/includes/footer.html
{% load static %}

{% load cache %}

<style>
    .footer-links__title,
    .footer-contacts__title {
        font-size: 1.5em; /* Размер шрифта */
        font-weight: bold; /* Жирный шрифт */
    }
</style>

{% cache 500 footer %}
    <footer class="site__footer">
    <div class="site-footer">
        <div class="container">
            <div class="site-footer__widgets">
                <div class="row">
                    <div class="col-12 col-md-4">
                        <div class="site-footer__widget footer-links">
                            <p class="footer-links__title">Информация</p>
                            <ul class="footer-links__list">
                                <li class="footer-links__item"><a href="{% url 'pages:about' %}" class="footer-links__link">О нас</a></li>
                                <li class="footer-links__item"><a href="{% url 'pages:contacts' %}" class="footer-links__link">Контакты</a></li>
                                <li class="footer-links__item"><a href="{% url 'pages:terms' %}" class="footer-links__link">Пользовательское соглашение</a></li>
                                <li class="footer-links__item"><a href="{% url 'pages:confidential' %}" class="footer-links__link">Конфиденциальность</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="site-footer__widget footer-contacts">
                            <p class="footer-contacts__title">Наши контакты</p>
                            <ul class="footer-contacts__contacts">
                                <li>
                                    <a href="https://yandex.ru/map-widget/v1/?um=constructor%3A266979062e8e136221e4e64e6a69126ac4a03b47ca7c348c41a9394e7dcd1ef5&amp;source=constructor" target="_blank">
                                    <i class="footer-contacts__icon fas fa-globe-americas"></i> 404125, Волгоградская обл., Волжский,<br> ул. Пушкина 51д/317
                                    </a>
                                </li>
                                <li>
                                    <a href="mailto:autovlz@yandex.ru">
                                    <i class="footer-contacts__icon far fa-envelope"></i> autovlz@yandex.ru
                                    </a>
                                </li>
                                <li><i class="footer-contacts__icon fas fa-mobile-alt"></i><a href="tel:+79270669900">+7 (927) 066-99-00</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="site-footer__widget footer-contacts">
                            <p class="footer-contacts__title">Время работы</p>
                            <ul class="footer-contacts__contacts">
                                <li><i class="footer-contacts__icon far fa-clock"></i>Пн-Пт: 8:30-17:00</li>
                                <li><i class="footer-contacts__icon far fa-clock"></i>Суббота: выходной</li>
                                <li><i class="footer-contacts__icon far fa-clock"></i>Воскресенье: выходной</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="site-footer__bottom"></div>
        </div>
        <div class="totop">
            <div class="totop__body">
                <div class="totop__start"></div>
                <div class="totop__container container"></div>
                <div class="totop__end">
                    <button type="button" class="totop__button" aria-label="Пролистать обратно вверх">
                        <svg width="13px" height="8px">
                            <use xlink:href="/static/images/sprite.svg#arrow-rounded-up-13x8"></use>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div>
    </footer>
{% endcache %}

autoweb/templates/includes/page_header.html
<div class="page-header">
    <div class="page-header__container container">
        <div class="page-header__breadcrumb">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'shop:homepage' %}">Главная</a>
                        <svg class="breadcrumb-arrow" width="6px" height="9px">
                            <use xlink:href="/static/images/sprite.svg#arrow-rounded-right-6x9"></use>
                        </svg>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">{{ breadcrumb }}</li>
                </ol>
            </nav>
        </div>
        <div class="page-header__title">
            <h1>{{ breadcrumb }}</h1>
        </div>
    </div>
</div>

autoweb/templates/includes/pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="products-view__pagination">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link page-link--with-arrow" href="?page={{ page_obj.previous_page_number }}" aria-label="Предыдущая">
                <svg class="page-link__arrow page-link__arrow--left" aria-hidden="true" width="8px" height="13px">
                    <use xlink:href="/static/images/sprite.svg#arrow-rounded-left-8x13"></use>
                </svg>
            </a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if i == page_obj.number %}
                <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
                {% if i > page_obj.number|add:"-3" and i < page_obj.number|add:"3" %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link page-link--with-arrow" href="?page={{ page_obj.next_page_number }}" aria-label="Следующая">
                    <svg class="page-link__arrow page-link__arrow--right" aria-hidden="true" width="8px" height="13px">
                        <use xlink:href="/static/images/sprite.svg#arrow-rounded-right-8x13"></use>
                    </svg>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

autoweb/templates/includes/photoswipe.html
{% load static %}
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="pswp__bg"></div>
  <div class="pswp__scroll-wrap">
      <div class="pswp__container">
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
      </div>
      <div class="pswp__ui pswp__ui--hidden">
          <div class="pswp__top-bar">
              <div class="pswp__counter"></div>
              <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
              <!--<button class="pswp__button pswp__button&#45;&#45;share" title="Share"></button>-->
              <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
              <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
              <div class="pswp__preloader">
                  <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                          <div class="pswp__preloader__donut"></div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
              <div class="pswp__share-tooltip"></div>
          </div>
          <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
          <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
          <div class="pswp__caption">
              <div class="pswp__caption__center"></div>
          </div>
      </div>
  </div>
</div>

autoweb/templates/includes/product_card.html
{% load static %}

<style>
    .product-card a {
        color: inherit;
        text-decoration: none;
      }
</style>

<div class="products-list__item">
    <div class="product-card product-card--hidden-actions ">
        {% with product.images.first as first_image %}
            {% if first_image %}
                <div class="product-card__image product-image">
                    <a href="{{ product.get_absolute_url }}" class="product-image__body" aria-label="Изображение товара, перейти на страницу товара">
                        <img class="product-image__img" src="{{ first_image.image.url }}" alt="">
                    </a>
                </div>
            {% else %}
                <div class="product-card__image product-image">
                    <a href="{{ product.get_absolute_url }}" class="product-image__body">
                        <img class="product-image__img" src="{% static 'images/image-holder.webp' %}" alt="" aria-label="Изображение отсутствует, перейти на страницу товара">
                    </a>
                </div>
            {% endif %}
        {% endwith %}
        <div class="product-card__info">
            <div class="product-card__name">
                <a href="{{ product.get_absolute_url }}"><h5>{{ product.title }}</h5></a>
            </div>
            <ul class="product-card__features-list">
                <li>Категория: <a href="{{ product.category.get_absolute_url }}" aria-label="Перейти в связанную категорию">{{ product.category.title }}</a></li>
                <li>Подкатегория: <a href="{{ product.subcategory.get_absolute_url }}" aria-label="Перейти в связанную подкатегорию">{{ product.subcategory.title }}</a></li>
                <li>Производитель: <a href="{{ product.brand.get_absolute_url }}" aria-label="Перейти к связанному производителю">{{ product.brand.title }}</a></li>
                <li>Артикул: <a href="{{ product.get_absolute_url }}" aria-label="Перейти на страницу товара">{{ product.article }}</a></li>
            </ul>
        </div>
        {% comment %} <div class="product-card__info">
            <div class="product-card__name">
                <a href=""><h5></h5></a>
            </div>
            {% for key, value in specification_dict.items %}
            <ul class="product-card__features-list">
                <li>{{ key }}: {{ value }}</li>
            </ul>
            {% endfor %}
        </div> {% endcomment %}
        <div class="product-card__actions">
            <div class="product-card__availability">
                В наличии: <span class="text-success">{{ product.quantity }}</span>
            </div>
            <div class="product-card__prices">
                {{ product.price }} руб.
            </div>
            <form class="product-card__buttons" method="POST" action="{% url 'cart:cart_add' product.pk %}">
                {% csrf_token %}
                <div class="product__actions-item product__actions-item--addtocart">
                    <input class="btn btn-primary product-card__addtocart" type="submit" value="В корзину" aria-label="Добавить в корзину">
                    <input class="btn btn-secondary product-card__addtocart product-card__addtocart--list" type="submit" value="В корзину" aria-label="Добавить в корзину">
                </div>
            </form>
        </div>
    </div>
</div>