autoweb/autoweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'pages.views.page_forbidden'
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.socialaccount.urls')),
    path(
        'accounts/', include('allauth.socialaccount.providers.google.urls')
    ),
    path(
        'accounts/', include('allauth.socialaccount.providers.yandex.urls')
    ),
    path('auth/', include('authorization.urls')),
    path('profile/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

autoweb/cart/urls.py
from django.urls import path

from .views import (add_to_cart, cart, checkout, delete_cart_item,
                    thank_you_page, update_cart_item, update_user_checkout)

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<int:pk>/', add_to_cart, name='cart_add'),
    path('update-cart-item/', update_cart_item, name='update_cart_item'),
    path('delete/<int:pk>', delete_cart_item, name='cart_delete'),
    path('checkout/', checkout, name='checkout'),
    path(
        'update-user-checkout/', update_user_checkout, name='update_checkout'
    ),
    path(
        'checkout/thank-you/<int:pk>', thank_you_page, name='thank_you'
    ),
]

autoweb/users/urls.py
from django.urls import path

from .views import (AutoDeleteView, AutoListView,
                    CustomUserDeleteView, CustomUserUpdateView,
                    AddAutoView, profile, UpdateAutoView)

app_name = 'account'

urlpatterns = [
    path(
        '',
        profile,
        name='profile'
    ),
    path(
        'edit-profile/',
        CustomUserUpdateView.as_view(),
        name='edit_profile'
    ),
    path(
        'delete-profile/',
        CustomUserDeleteView.as_view(),
        name='delete_profile'
    ),
    path(
        'auto/',
        AutoListView.as_view(),
        name='users_auto'
    ),
    path(
        'add-auto/',
        AddAutoView.as_view(),
        name='add_auto'
    ),
    path(
        'edit-auto/<int:auto_pk>/',
        UpdateAutoView.as_view(),
        name='edit_auto'
    ),
    path(
        'delete-auto/<int:auto_pk>/',
        AutoDeleteView.as_view(),
        name='delete_auto'
    ),
]

autoweb/templates/profile/add_auto.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Добавить автомобиль</h5>
                    </div>
                    <div class="card-divider"></div>
                    <div class="card-body">
                        <div class="row no-gutters">
                            <div class="card shadow-sm p-3 mb-2 bg-body rounded">
                                <div class="card-body">
                                
                                    <form method="post" action="{% url 'account:add_auto' %}">
                                        {% csrf_token %}
                                        
                                        {% for field in form %}
                                            <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                                                {% bootstrap_field field form_group_class='my_custom_class' %}
                                            </div>
                                        {% endfor %}
                                        
                                        <div class="form-group mt-5 mb-0">
                                            <button class="btn btn-primary" aria-label="Добавить автомобиль">Добавить</button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

autoweb/templates/profile/delete_auto.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Удалить автомобиль</h5>
                    </div>
                    <div class="card-divider"></div>
                    <div class="card-body">
                        <div class="row no-gutters">

                                <div class="card-body">
                                
                                    <form method="post">
                                        {% csrf_token %}
                                        <p>Вы уверены, что хотите удалить автомобиль: {{ object.mark }} {{ object.model }} ?</p>
                                        {{ form }}
                                        
                                        <div class="form-group mt-5 mb-0">
                                            <button type="submit" class="btn btn-primary" aria-label="Подтвердить удаление">Конечно!</button>
                                        </div>
                                    </form>

                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

autoweb/templates/profile/delete_profile.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Удалить профиль</h5>
                    </div>
                    <div class="card-divider"></div>
                    <div class="card-body">
                        <div class="row no-gutters">
                            <div class="card-body">
                            
                                <form method="post">
                                    {% csrf_token %}
                                    <p>Вы уверены, что хотите удалить профиль?</p>
                                    <p>Все сохранённые данные, включая историю заказов, перестанут быть доступными.</p>

                                    <div class="form-group mt-5 mb-0">
                                        <button type="submit" class="btn btn-primary" aria-label="Подтвердить удаление">Конечно!</button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

autoweb/templates/profile/edit_auto.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Редактировать автомобиль</h5>
                    </div>
                    <div class="card-divider"></div>
                    <div class="card-body">
                        <div class="row no-gutters">
                            <div class="card shadow-sm p-3 mb-2 bg-body rounded">
                                <div class="card-body">
                                
                                    <form method="post" action="{% url 'account:edit_auto' auto.id %}">
                                        {% csrf_token %}
                                        
                                        {% for field in form %}
                                            <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                                                {% bootstrap_field field form_group_class='my_custom_class' %}
                                            </div>
                                        {% endfor %}
                                        
                                        <div class="form-group mt-5 mb-0">
                                            <button class="btn btn-primary" aria-label="Подтвердить изменения">Подтвердить изменения</button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

autoweb/templates/profile/edit_profile.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Редактировать профиль</h5>
                    </div>
                    <div class="card-divider"></div>
                    <div class="card-body">
                        <div class="row no-gutters">

                                <div class="col-12 col-lg-7 col-xl-6">
                                
                                    <form method="post" action="{% url 'account:edit_profile' %}">
                                        {% csrf_token %}
                                        
                                        {% for field in form %}
                                            <div class="form-group mb-3{% if field.errors %} has-error{% endif %}">
                                                {% bootstrap_field field form_group_class='my_custom_class' %}
                                            </div>
                                        {% endfor %}
                                        
                                        <div class="form-group mt-5 mb-0">
                                            <button class="btn btn-primary" aria-label="Подтвердить изменения">Подтвердить изменения</button>
                                        </div>
                                    </form>
                                </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

autoweb/templates/profile/profile.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<style>
    .address-card__footer a {
        color: #000000; /* Измените этот цвет на желаемый */
        text-decoration: none;
    }
    .address-card__footer a:hover {
        color: #000000; /* Измените этот цвет на желаемый для hover state */
        text-decoration: none;
    }
</style>
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Страница пользователя</h5>
                    </div>
                    <div class="card-divider"></div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="card shadow-sm p-3 mb-2 bg-body rounded">
                                    <div class="card-body">
                                        <form>
                                            <div class="mb-3">
                                                <label for="{{ form.email.id_for_label }}" class="form-label">Электронная почта</label>
                                                <input type="text" class="form-control" id="{{ form.email.id_for_label }}" value="{{ user.email }}" disabled style="background-color: white;" aria-label="Поле электронной почты">
                                            </div>
                                            <div class="mb-3">
                                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                                <input type="text" class="form-control" id="{{ form.first_name.id_for_label }}" value="{{ user.first_name }}" disabled style="background-color: white;" aria-label="Поле имени пользователя">
                                            </div>
                                            <div class="mb-3">
                                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                                <input type="text" class="form-control" id="{{ form.last_name.id_for_label }}" value="{{ user.last_name }}" disabled style="background-color: white;" aria-label="Поле фамилии пользователя">
                                            </div>
                                            <div class="mb-3">
                                                <label for="{{ form.phone_number.id_for_label }}" class="form-label">Номер телефона</label>
                                                <input type="text" class="form-control" id="{{ form.phone_number.id_for_label }}" value="{{ user.phone_number }}" disabled style="background-color: white;" aria-label="Поле номера телефона пользователя">
                                            </div>
                                        </form>
                                    </div>
                                    <a href="{% url 'account:edit_profile' %}" class="btn btn-primary">Редактировать профиль</a>
                                    </br>
                                    <a href="{% url 'account:delete_profile' %}" class="btn btn-primary">Удалить профиль</a>
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                {% for car in cars %}
                                    <div class="card shadow-sm p-3 mb-2 bg-body rounded">
                                        <div class="card-body">
                                            <h7 class="card-title">{{ car.mark }} {{ car.model }}</h7>
                                            <hr>
                                            <p class="card-subtitle mb-2 text-muted">VIN-код: {% if car.vin_code %}{{ car.vin_code }}{% else %}Не указан{% endif %}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

autoweb/templates/profile/users_auto.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block content %}
<style>
    .address-card__footer a {
        color: #000000; /* Измените этот цвет на желаемый */
        text-decoration: none;
    }
    .address-card__footer a:hover {
        color: #000000; /* Измените этот цвет на желаемый для hover state */
        text-decoration: none;
    }
</style>
<div class="block">
    <div class="container">
        <div class="row">
            {% include "includes/account_navigation.html" %}
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="addresses-list">
                    <a href="{% url 'account:add_auto' %}" class="addresses-list__item addresses-list__item--new">
                        <div class="addresses-list__plus"></div>
                        <div class="btn btn-secondary btn-sm">Новый автомобиль</div>
                    </a>
                    {% for car in cars %}
                    <div class="addresses-list__divider"></div>
                    <div class="addresses-list__item card address-card">
                        <div class="address-card__body">
                            <div class="address-card__name">{{ car.mark }} {% if car.model %}{{ car.model }}{% endif %}</div>
                            <div class="address-card__row">
                                <div class="address-card__row-title">VIN-код</div>
                                <div class="address-card__row-content">{% if car.vin_code %}{{ car.vin_code }}{% else %}Не указан{% endif %}</div>
                            </div>
                            <div class="address-card__footer">
                                <a href="{% url 'account:edit_auto' car.id %}">Редактировать</a>&nbsp;&nbsp;
                                <a href="{% url 'account:delete_auto' car.id %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}